name: Release

on:
  release:
    types: [released]

concurrency:
  group: release
  cancel-in-progress: false

jobs:

  release:
    runs-on: ubuntu-latest
    container:
      image: python:3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload
        run: |
          pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  publish-to-pypi:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/troposphere-dns-certificate/
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          verbose: true
